package com.rawal.Todos.Models;

import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@DynamoDBTable(tableName = "Todos")
@Entity
@Data
@NoArgsConstructor
@RequiredArgsConstructor
public class Todo {
	
	@DynamoDBTyped(DynamoDBAttributeType.S)
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	@Id
	private String id;

	@DynamoDBTyped(DynamoDBAttributeType.S)
	@DynamoDBAttribute
	@NonNull
	private String task;
	
	@DynamoDBTyped(DynamoDBAttributeType.S)
	@DynamoDBAttribute
	@NonNull
	private String description;

	@DynamoDBTypeConverted(converter = LocalDateStringConverter.class)
	@DynamoDBAttribute
	@NonNull
	private LocalDate createdOn;
	
	@DynamoDBTypeConverted(converter = LocalDateStringConverter.class)
	@DynamoDBAttribute
	@NonNull
	private LocalDate dueOn;

	@DynamoDBTyped(DynamoDBAttributeType.S)
	@DynamoDBAttribute
	@NonNull
	private String createdBy;

	@DynamoDBTyped(DynamoDBAttributeType.N)
	@DynamoDBAttribute
	@NonNull
	private Boolean isCompleted;

	// @DynamoDBAttribute
	// @Version
	// private Long version;

}